#ifndef _DO_STRING_H
#define _DO_STRING_H

const char *syscallnames[] = {
	"__NR_restart_syscall	",//__NR_SYSCALL_BASE+  0)
	"__NR_exit			",//__NR_SYSCALL_BASE+  1)
	"__NR_fork			",//__NR_SYSCALL_BASE+  2)
	"__NR_read			",//__NR_SYSCALL_BASE+  3)
	"__NR_write		",//__NR_SYSCALL_BASE+  4)
	"__NR_open			",//__NR_SYSCALL_BASE+  5)
	"__NR_close		",//__NR_SYSCALL_BASE+  6)
	"sys_waitpid", /* 7 was sys_waitpid */
	"__NR_creat		",//__NR_SYSCALL_BASE+  8)
	"__NR_link			",//__NR_SYSCALL_BASE+  9)
	"__NR_unlink		",//__NR_SYSCALL_BASE+ 10)
	"__NR_execve		",//__NR_SYSCALL_BASE+ 11)
	"__NR_chdir		",//__NR_SYSCALL_BASE+ 12)
	"__NR_time			",//__NR_SYSCALL_BASE+ 13)
	"__NR_mknod		",//__NR_SYSCALL_BASE+ 14)
	"__NR_chmod		",//__NR_SYSCALL_BASE+ 15)
	"__NR_lchown		",//__NR_SYSCALL_BASE+ 16)
	"sys_break", /* 17 was sys_break */
	"sys_stat", /* 18 was sys_stat */
	"__NR_lseek		",//__NR_SYSCALL_BASE+ 19)
	"__NR_getpid		",//__NR_SYSCALL_BASE+ 20)
	"__NR_mount		",//__NR_SYSCALL_BASE+ 21)
	"__NR_umount		",//__NR_SYSCALL_BASE+ 22)
	"__NR_setuid		",//__NR_SYSCALL_BASE+ 23)
	"__NR_getuid		",//__NR_SYSCALL_BASE+ 24)
	"__NR_stime		",//__NR_SYSCALL_BASE+ 25)
	"__NR_ptrace		",//__NR_SYSCALL_BASE+ 26)
	"__NR_alarm		",//__NR_SYSCALL_BASE+ 27)
	"sys_fstat", /* 28 was sys_fstat */
	"__NR_pause		",//__NR_SYSCALL_BASE+ 29)
	"__NR_utime		",//__NR_SYSCALL_BASE+ 30)
	"sys_stty", /* 31 was sys_stty */
	"sys_gtty", /* 32 was sys_gtty */
	"__NR_access		",//__NR_SYSCALL_BASE+ 33)
	"__NR_nice			",//__NR_SYSCALL_BASE+ 34)
	"sys_ftime", /* 35 was sys_ftime */
	"__NR_sync		",//__NR_SYSCALL_BASE+ 36)
	"__NR_kill		",//__NR_SYSCALL_BASE+ 37)
	"__NR_rename		",//__NR_SYSCALL_BASE+ 38)
	"__NR_mkdir		",//__NR_SYSCALL_BASE+ 39)
	"__NR_rmdir		",//__NR_SYSCALL_BASE+ 40)
	"__NR_dup		",//__NR_SYSCALL_BASE+ 41)
	"__NR_pipe		",//__NR_SYSCALL_BASE+ 42)
	"__NR_times		",//__NR_SYSCALL_BASE+ 43)
	"sys_prof", /* 44 was sys_prof */
	"__NR_brk		",//__NR_SYSCALL_BASE+ 45)
	"__NR_setgid		",//__NR_SYSCALL_BASE+ 46)
	"__NR_getgid		",//__NR_SYSCALL_BASE+ 47)
	"sys_signal", /* 48 was sys_signal */
	"__NR_geteuid		",//__NR_SYSCALL_BASE+ 49)
	"__NR_getegid		",//__NR_SYSCALL_BASE+ 50)
	"__NR_acct		",//__NR_SYSCALL_BASE+ 51)
	"__NR_umount2		",//__NR_SYSCALL_BASE+ 52)
	"sys_lock", /* 53 was sys_lock */
	"__NR_ioctl		",//__NR_SYSCALL_BASE+ 54)
	"__NR_fcntl		",//__NR_SYSCALL_BASE+ 55)
	"sys_mps", /* 56 was sys_mpx */
	"__NR_setpgid		",//__NR_SYSCALL_BASE+ 57)
	"sys_ulimit", /* 58 was sys_ulimit */
	"sys_olduname", /* 59 was sys_olduname */
	"__NR_umask		",//__NR_SYSCALL_BASE+ 60)
	"__NR_chroot		",//__NR_SYSCALL_BASE+ 61)
	"__NR_ustat		",//__NR_SYSCALL_BASE+ 62)
	"__NR_dup2		",//__NR_SYSCALL_BASE+ 63)
	"__NR_getppid		",//__NR_SYSCALL_BASE+ 64)
	"__NR_getpgrp		",//__NR_SYSCALL_BASE+ 65)
	"__NR_setsid		",//__NR_SYSCALL_BASE+ 66)
	"__NR_sigaction		",//__NR_SYSCALL_BASE+ 67)
	"sys_sgetmask", /* 68 was sys_sgetmask */
	"sys_ssetmask", /* 69 was sys_ssetmask */
	"__NR_setreuid		",//__NR_SYSCALL_BASE+ 70)
	"__NR_setregid		",//__NR_SYSCALL_BASE+ 71)
	"__NR_sigsuspend		",//__NR_SYSCALL_BASE+ 72)
	"__NR_sigpending		",//__NR_SYSCALL_BASE+ 73)
	"__NR_sethostname	",//__NR_SYSCALL_BASE+ 74)
	"__NR_setrlimit		",//__NR_SYSCALL_BASE+ 75)
	"__NR_getrlimit		",//__NR_SYSCALL_BASE+ 76)	/* Back compat 2GB limited rlimit */
	"__NR_getrusage		",//__NR_SYSCALL_BASE+ 77)
	"__NR_gettimeofday	",//__NR_SYSCALL_BASE+ 78)
	"__NR_settimeofday	",//__NR_SYSCALL_BASE+ 79)
	"__NR_getgroups		",//__NR_SYSCALL_BASE+ 80)
	"__NR_setgroups		",//__NR_SYSCALL_BASE+ 81)
	"__NR_select		",//__NR_SYSCALL_BASE+ 82)
	"__NR_symlink		",//__NR_SYSCALL_BASE+ 83)
	"sys_lstat", /* 84 was sys_lstat */
	"__NR_readlink		",//__NR_SYSCALL_BASE+ 85)
	"__NR_uselib		",//__NR_SYSCALL_BASE+ 86)
	"__NR_swapon		",//__NR_SYSCALL_BASE+ 87)
	"__NR_reboot		",//__NR_SYSCALL_BASE+ 88)
	"__NR_readdir		",//__NR_SYSCALL_BASE+ 89)
	"__NR_mmap		",//__NR_SYSCALL_BASE+ 90)
	"__NR_munmap		",//__NR_SYSCALL_BASE+ 91)
	"__NR_truncate		",//__NR_SYSCALL_BASE+ 92)
	"__NR_ftruncate		",//__NR_SYSCALL_BASE+ 93)
	"__NR_fchmod		",//__NR_SYSCALL_BASE+ 94)
	"__NR_fchown		",//__NR_SYSCALL_BASE+ 95)
	"__NR_getpriority	",//__NR_SYSCALL_BASE+ 96)
	"__NR_setpriority	",//__NR_SYSCALL_BASE+ 97)
	"sys_profil",	/* 98 was sys_profil */
	"__NR_statfs		",//__NR_SYSCALL_BASE+ 99)
	"__NR_fstatfs		",//__NR_SYSCALL_BASE+100)
	"sys_ioperm", /* 101 was sys_ioperm */
	"__NR_socketcall		",//__NR_SYSCALL_BASE+102)
	"__NR_syslog		",//__NR_SYSCALL_BASE+103)
	"__NR_setitimer		",//__NR_SYSCALL_BASE+104)
	"__NR_getitimer		",//__NR_SYSCALL_BASE+105)
	"__NR_stat		",//__NR_SYSCALL_BASE+106)
	"__NR_lstat		",//__NR_SYSCALL_BASE+107)
	"__NR_fstat		",//__NR_SYSCALL_BASE+108)
	"sys_unam", /* 109 was sys_uname */
	"sys_iopl", /* 110 was sys_iopl */
	"__NR_vhangup		",//__NR_SYSCALL_BASE+111)
	"sys_idle", /* 112 was sys_idle */
	"__NR_syscall		",//__NR_SYSCALL_BASE+113) /* syscall to call a syscall! */
	"__NR_wait4		",//__NR_SYSCALL_BASE+114)
	"__NR_swapoff		",//__NR_SYSCALL_BASE+115)
	"__NR_sysinfo		",//__NR_SYSCALL_BASE+116)
	"__NR_ipc		",//__NR_SYSCALL_BASE+117)
	"__NR_fsync		",//__NR_SYSCALL_BASE+118)
	"__NR_sigreturn		",//__NR_SYSCALL_BASE+119)
	"__NR_clone		",//__NR_SYSCALL_BASE+120)
	"__NR_setdomainname	",//__NR_SYSCALL_BASE+121)
	"__NR_uname		",//__NR_SYSCALL_BASE+122)
	"sys_modify_ld", /* 123 was sys_modify_ldt */
	"__NR_adjtimex		",//__NR_SYSCALL_BASE+124)
	"__NR_mprotect		",//__NR_SYSCALL_BASE+125)
	"__NR_sigprocmask	",//__NR_SYSCALL_BASE+126)
	"sys_create_module", /* 127 was sys_create_module */
	"__NR_init_module	",//__NR_SYSCALL_BASE+128)
	"__NR_delete_module	",//__NR_SYSCALL_BASE+129)
	"sys_get_kernel_syms", /* 130 was sys_get_kernel_syms */
	"__NR_quotactl		",//__NR_SYSCALL_BASE+131)
	"__NR_getpgid		",//__NR_SYSCALL_BASE+132)
	"__NR_fchdir		",//__NR_SYSCALL_BASE+133)
	"__NR_bdflush		",//__NR_SYSCALL_BASE+134)
	"__NR_sysfs		",//__NR_SYSCALL_BASE+135)
	"__NR_personality	",//__NR_SYSCALL_BASE+136)
	"sys_afs_syscall", /* 137 was sys_afs_syscall */
	"__NR_setfsuid		",//__NR_SYSCALL_BASE+138)
	"__NR_setfsgid		",//__NR_SYSCALL_BASE+139)
	"__NR__llseek		",//__NR_SYSCALL_BASE+140)
	"__NR_getdents		",//__NR_SYSCALL_BASE+141)
	"__NR__newselect		",//__NR_SYSCALL_BASE+142)
	"__NR_flock		",//__NR_SYSCALL_BASE+143)
	"__NR_msync		",//__NR_SYSCALL_BASE+144)
	"__NR_readv		",//__NR_SYSCALL_BASE+145)
	"__NR_writev		",//__NR_SYSCALL_BASE+146)
	"__NR_getsid		",//__NR_SYSCALL_BASE+147)
	"__NR_fdatasync		",//__NR_SYSCALL_BASE+148)
	"__NR__sysctl		",//__NR_SYSCALL_BASE+149)
	"__NR_mlock		",//__NR_SYSCALL_BASE+150)
	"__NR_munlock		",//__NR_SYSCALL_BASE+151)
	"__NR_mlockall		",//__NR_SYSCALL_BASE+152)
	"__NR_munlockall		",//__NR_SYSCALL_BASE+153)
	"__NR_sched_setparam	",//__NR_SYSCALL_BASE+154)
	"__NR_sched_getparam	",//__NR_SYSCALL_BASE+155)
	"__NR_sched_setscheduler	",//__NR_SYSCALL_BASE+156)
	"__NR_sched_getscheduler	",//__NR_SYSCALL_BASE+157)
	"__NR_sched_yield	",//__NR_SYSCALL_BASE+158)
	"__NR_sched_get_priority_max",//__NR_SYSCALL_BASE+159)
	"__NR_sched_get_priority_min",//__NR_SYSCALL_BASE+160)
	"__NR_sched_rr_get_interval",//__NR_SYSCALL_BASE+161)
	"__NR_nanosleep		",//__NR_SYSCALL_BASE+162)
	"__NR_mremap		",//__NR_SYSCALL_BASE+163)
	"__NR_setresuid		",//__NR_SYSCALL_BASE+164)
	"__NR_getresuid		",//__NR_SYSCALL_BASE+165)
	"sys_vm86", /* 166 was sys_vm86 */
	"sys_query_module", /* 167 was sys_query_module */
	"__NR_poll		",//__NR_SYSCALL_BASE+168)
	"__NR_nfsservctl		",//__NR_SYSCALL_BASE+169)
	"__NR_setresgid		",//__NR_SYSCALL_BASE+170)
	"__NR_getresgid		",//__NR_SYSCALL_BASE+171)
	"__NR_prctl		",//__NR_SYSCALL_BASE+172)
	"__NR_rt_sigreturn	",//__NR_SYSCALL_BASE+173)
	"__NR_rt_sigaction	",//__NR_SYSCALL_BASE+174)
	"__NR_rt_sigprocmask	",//__NR_SYSCALL_BASE+175)
	"__NR_rt_sigpending	",//__NR_SYSCALL_BASE+176)
	"__NR_rt_sigtimedwait	",//__NR_SYSCALL_BASE+177)
	"__NR_rt_sigqueueinfo	",//__NR_SYSCALL_BASE+178)
	"__NR_rt_sigsuspend	",//__NR_SYSCALL_BASE+179)
	"__NR_pread64		",//__NR_SYSCALL_BASE+180)
	"__NR_pwrite64		",//__NR_SYSCALL_BASE+181)
	"__NR_chown		",//__NR_SYSCALL_BASE+182)
	"__NR_getcwd		",//__NR_SYSCALL_BASE+183)
	"__NR_capget		",//__NR_SYSCALL_BASE+184)
	"__NR_capset		",//__NR_SYSCALL_BASE+185)
	"__NR_sigaltstack	",//__NR_SYSCALL_BASE+186)
	"__NR_sendfile		",//__NR_SYSCALL_BASE+187)
	"188", /* 188 reserved */
	"189",					/* 189 reserved */
	"__NR_vfork		",//__NR_SYSCALL_BASE+190)
	"__NR_ugetrlimit		",//__NR_SYSCALL_BASE+191)	/* SuS compliant getrlimit */
	"__NR_mmap2		",//__NR_SYSCALL_BASE+192)
	"__NR_truncate64		",//__NR_SYSCALL_BASE+193)
	"__NR_ftruncate64	",//__NR_SYSCALL_BASE+194)
	"__NR_stat64		",//__NR_SYSCALL_BASE+195)
	"__NR_lstat64		",//__NR_SYSCALL_BASE+196)
	"__NR_fstat64		",//__NR_SYSCALL_BASE+197)
	"__NR_lchown32		",//__NR_SYSCALL_BASE+198)
	"__NR_getuid32		",//__NR_SYSCALL_BASE+199)
	"__NR_getgid32		",//__NR_SYSCALL_BASE+200)
	"__NR_geteuid32		",//__NR_SYSCALL_BASE+201)
	"__NR_getegid32		",//__NR_SYSCALL_BASE+202)
	"__NR_setreuid32		",//__NR_SYSCALL_BASE+203)
	"__NR_setregid32		",//__NR_SYSCALL_BASE+204)
	"__NR_getgroups32	",//__NR_SYSCALL_BASE+205)
	"__NR_setgroups32	",//__NR_SYSCALL_BASE+206)
	"__NR_fchown32		",//__NR_SYSCALL_BASE+207)
	"__NR_setresuid32	",//__NR_SYSCALL_BASE+208)
	"__NR_getresuid32	",//__NR_SYSCALL_BASE+209)
	"__NR_setresgid32	",//__NR_SYSCALL_BASE+210)
	"__NR_getresgid32	",//__NR_SYSCALL_BASE+211)
	"__NR_chown32		",//__NR_SYSCALL_BASE+212)
	"__NR_setuid32		",//__NR_SYSCALL_BASE+213)
	"__NR_setgid32		",//__NR_SYSCALL_BASE+214)
	"__NR_setfsuid32		",//__NR_SYSCALL_BASE+215)
	"__NR_setfsgid32		",//__NR_SYSCALL_BASE+216)
	"__NR_getdents64		",//__NR_SYSCALL_BASE+217)
	"__NR_pivot_root		",//__NR_SYSCALL_BASE+218)
	"__NR_mincore		",//__NR_SYSCALL_BASE+219)
	"__NR_madvise		",//__NR_SYSCALL_BASE+220)
	"__NR_fcntl64		",//__NR_SYSCALL_BASE+221)
	"tus", /* 222 for tux */
	"unused", /* 223 is unused */
	"__NR_gettid		",//__NR_SYSCALL_BASE+224)
	"__NR_readahead		",//__NR_SYSCALL_BASE+225)
	"__NR_setxattr		",//__NR_SYSCALL_BASE+226)
	"__NR_lsetxattr		",//__NR_SYSCALL_BASE+227)
	"__NR_fsetxattr		",//__NR_SYSCALL_BASE+228)
	"__NR_getxattr		",//__NR_SYSCALL_BASE+229)
	"__NR_lgetxattr		",//__NR_SYSCALL_BASE+230)
	"__NR_fgetxattr		",//__NR_SYSCALL_BASE+231)
	"__NR_listxattr		",//__NR_SYSCALL_BASE+232)
	"__NR_llistxattr		",//__NR_SYSCALL_BASE+233)
	"__NR_flistxattr		",//__NR_SYSCALL_BASE+234)
	"__NR_removexattr	",//__NR_SYSCALL_BASE+235)
	"__NR_lremovexattr	",//__NR_SYSCALL_BASE+236)
	"__NR_fremovexattr	",//__NR_SYSCALL_BASE+237)
	"__NR_tkill		",//__NR_SYSCALL_BASE+238)
	"__NR_sendfile64		",//__NR_SYSCALL_BASE+239)
	"__NR_futex		",//__NR_SYSCALL_BASE+240)
	"__NR_sched_setaffinity	",//__NR_SYSCALL_BASE+241)
	"__NR_sched_getaffinity	",//__NR_SYSCALL_BASE+242)
	"__NR_io_setup		",//__NR_SYSCALL_BASE+243)
	"__NR_io_destroy		",//__NR_SYSCALL_BASE+244)
	"__NR_io_getevents	",//__NR_SYSCALL_BASE+245)
	"__NR_io_submit		",//__NR_SYSCALL_BASE+246)
	"__NR_io_cancel		",//__NR_SYSCALL_BASE+247)
	"__NR_exit_group		",//__NR_SYSCALL_BASE+248)
	"__NR_lookup_dcookie	",//__NR_SYSCALL_BASE+249)
	"__NR_epoll_create	",//__NR_SYSCALL_BASE+250)
	"__NR_epoll_ctl		",//__NR_SYSCALL_BASE+251)
	"__NR_epoll_wait		",//__NR_SYSCALL_BASE+252)
	"__NR_remap_file_pages	",//__NR_SYSCALL_BASE+253)
	"set_thread_area", /* 254 for set_thread_area */
	"get_thread_area",/* 255 for get_thread_area */
	"__NR_set_tid_address	",//__NR_SYSCALL_BASE+256)
	"__NR_timer_create	",//__NR_SYSCALL_BASE+257)
	"__NR_timer_settime	",//__NR_SYSCALL_BASE+258)
	"__NR_timer_gettime	",//__NR_SYSCALL_BASE+259)
	"__NR_timer_getoverrun	",//__NR_SYSCALL_BASE+260)
	"__NR_timer_delete	",//__NR_SYSCALL_BASE+261)
	"__NR_clock_settime	",//__NR_SYSCALL_BASE+262)
	"__NR_clock_gettime	",//__NR_SYSCALL_BASE+263)
	"__NR_clock_getres	",//__NR_SYSCALL_BASE+264)
	"__NR_clock_nanosleep	",//__NR_SYSCALL_BASE+265)
	"__NR_statfs64		",//__NR_SYSCALL_BASE+266)
	"__NR_fstatfs64		",//__NR_SYSCALL_BASE+267)
	"__NR_tgkill		",//__NR_SYSCALL_BASE+268)
	"__NR_utimes		",//__NR_SYSCALL_BASE+269)
	"__NR_arm_fadvise64_64	",//__NR_SYSCALL_BASE+270)
	"__NR_pciconfig_iobase	",//__NR_SYSCALL_BASE+271)
	"__NR_pciconfig_read	",//__NR_SYSCALL_BASE+272)
	"__NR_pciconfig_write	",//__NR_SYSCALL_BASE+273)
	"__NR_mq_open		",//__NR_SYSCALL_BASE+274)
	"__NR_mq_unlink		",//__NR_SYSCALL_BASE+275)
	"__NR_mq_timedsend	",//__NR_SYSCALL_BASE+276)
	"__NR_mq_timedreceive	",//__NR_SYSCALL_BASE+277)
	"__NR_mq_notify		",//__NR_SYSCALL_BASE+278)
	"__NR_mq_getsetattr	",//__NR_SYSCALL_BASE+279)
	"__NR_waitid		",//__NR_SYSCALL_BASE+280)
	"__NR_socket		",//__NR_SYSCALL_BASE+281)
	"__NR_bind		",//__NR_SYSCALL_BASE+282)
	"__NR_connect		",//__NR_SYSCALL_BASE+283)
	"__NR_listen		",//__NR_SYSCALL_BASE+284)
	"__NR_accept		",//__NR_SYSCALL_BASE+285)
	"__NR_getsockname	",//__NR_SYSCALL_BASE+286)
	"__NR_getpeername	",//__NR_SYSCALL_BASE+287)
	"__NR_socketpair		",//__NR_SYSCALL_BASE+288)
	"__NR_send		",//__NR_SYSCALL_BASE+289)
	"__NR_sendto		",//__NR_SYSCALL_BASE+290)
	"__NR_recv		",//__NR_SYSCALL_BASE+291)
	"__NR_recvfrom		",//__NR_SYSCALL_BASE+292)
	"__NR_shutdown		",//__NR_SYSCALL_BASE+293)
	"__NR_setsockopt		",//__NR_SYSCALL_BASE+294)
	"__NR_getsockopt		",//__NR_SYSCALL_BASE+295)
	"__NR_sendmsg		",//__NR_SYSCALL_BASE+296)
	"__NR_recvmsg		",//__NR_SYSCALL_BASE+297)
	"__NR_semop		",//__NR_SYSCALL_BASE+298)
	"__NR_semget		",//__NR_SYSCALL_BASE+299)
	"__NR_semctl		",//__NR_SYSCALL_BASE+300)
	"__NR_msgsnd		",//__NR_SYSCALL_BASE+301)
	"__NR_msgrcv		",//__NR_SYSCALL_BASE+302)
	"__NR_msgget		",//__NR_SYSCALL_BASE+303)
	"__NR_msgctl		",//__NR_SYSCALL_BASE+304)
	"__NR_shmat		",//__NR_SYSCALL_BASE+305)
	"__NR_shmdt		",//__NR_SYSCALL_BASE+306)
	"__NR_shmget		",//__NR_SYSCALL_BASE+307)
	"__NR_shmctl		",//__NR_SYSCALL_BASE+308)
	"__NR_add_key		",//__NR_SYSCALL_BASE+309)
	"__NR_request_key	",//__NR_SYSCALL_BASE+310)
	"__NR_keyctl		",//__NR_SYSCALL_BASE+311)
	"__NR_semtimedop		",//__NR_SYSCALL_BASE+312)
	"__NR_vserver		",//__NR_SYSCALL_BASE+313)
	"__NR_ioprio_set		",//__NR_SYSCALL_BASE+314)
	"__NR_ioprio_get		",//__NR_SYSCALL_BASE+315)
	"__NR_inotify_init	",//__NR_SYSCALL_BASE+316)
	"__NR_inotify_add_watch	",//__NR_SYSCALL_BASE+317)
	"__NR_inotify_rm_watch	",//__NR_SYSCALL_BASE+318)
	"__NR_mbind		",//__NR_SYSCALL_BASE+319)
	"__NR_get_mempolicy	",//__NR_SYSCALL_BASE+320)
	"__NR_set_mempolicy	",//__NR_SYSCALL_BASE+321)
	"__NR_openat		",//__NR_SYSCALL_BASE+322)
	"__NR_mkdirat		",//__NR_SYSCALL_BASE+323)
	"__NR_mknodat		",//__NR_SYSCALL_BASE+324)
	"__NR_fchownat		",//__NR_SYSCALL_BASE+325)
	"__NR_futimesat		",//__NR_SYSCALL_BASE+326)
	"__NR_fstatat64		",//__NR_SYSCALL_BASE+327)
	"__NR_unlinkat		",//__NR_SYSCALL_BASE+328)
	"__NR_renameat		",//__NR_SYSCALL_BASE+329)
	"__NR_linkat			",//__NR_SYSCALL_BASE+330)
	"__NR_symlinkat	",//__NR_SYSCALL_BASE+331)
	"__NR_readlinkat	",//__NR_SYSCALL_BASE+332)
	"__NR_fchmodat		",//__NR_SYSCALL_BASE+333)
	"__NR_faccessat	",//__NR_SYSCALL_BASE+334)
	"__NR_pselect6		",//__NR_SYSCALL_BASE+335)
	"__NR_ppoll			",//__NR_SYSCALL_BASE+336)
	"__NR_unshare		",//__NR_SYSCALL_BASE+337)
	"__NR_set_robust_list	",//__NR_SYSCALL_BASE+338)
	"__NR_get_robust_list	",//__NR_SYSCALL_BASE+339)
	"__NR_splice			",//__NR_SYSCALL_BASE+340)
	"__NR_arm_sync_file_range",//__NR_SYSCALL_BASE+341)
	"__NR_tee				",//__NR_SYSCALL_BASE+342)
	"__NR_vmsplice		",//__NR_SYSCALL_BASE+343)
	"__NR_move_pages	",//__NR_SYSCALL_BASE+344)
	"__NR_getcpu			",//__NR_SYSCALL_BASE+345)
	"__NR_epoll_pwait	",//__NR_SYSCALL_BASE+346)
	"__NR_kexec_load		",//__NR_SYSCALL_BASE+347)
	"__NR_utimensat		",//__NR_SYSCALL_BASE+348)
	"__NR_signalfd		",//__NR_SYSCALL_BASE+349)
	"__NR_timerfd_create	",//__NR_SYSCALL_BASE+350)
	"__NR_eventfd		",//__NR_SYSCALL_BASE+351)
	"__NR_fallocate		",//__NR_SYSCALL_BASE+352)
	"__NR_timerfd_settime	",//__NR_SYSCALL_BASE+353)
	"__NR_timerfd_gettime	",//__NR_SYSCALL_BASE+354)
	"__NR_signalfd4		",//__NR_SYSCALL_BASE+355)
	"__NR_eventfd2		",//__NR_SYSCALL_BASE+356)
	"__NR_epoll_create1	",//__NR_SYSCALL_BASE+357)
	"__NR_dup3		",//__NR_SYSCALL_BASE+358)
	"__NR_pipe2		",//__NR_SYSCALL_BASE+359)
	"__NR_inotify_init1	",//__NR_SYSCALL_BASE+360)
	"__NR_preadv		",//__NR_SYSCALL_BASE+361)
	"__NR_pwritev		",//__NR_SYSCALL_BASE+362)
	"__NR_rt_tgsigqueueinfo	",//__NR_SYSCALL_BASE+363)
	"__NR_perf_event_open	",//__NR_SYSCALL_BASE+364)
	"__NR_recvmmsg		",//__NR_SYSCALL_BASE+365)
	"__NR_accept4		",//__NR_SYSCALL_BASE+366)
	"__NR_fanotify_init	",//__NR_SYSCALL_BASE+367)
	"__NR_fanotify_mark	",//__NR_SYSCALL_BASE+368)
	"__NR_prlimit64		",//__NR_SYSCALL_BASE+369)
	"__NR_name_to_handle_at	",//__NR_SYSCALL_BASE+370)
	"__NR_open_by_handle_at	",//__NR_SYSCALL_BASE+371)
	"__NR_clock_adjtime	",//__NR_SYSCALL_BASE+372)
	"__NR_syncfs		",//__NR_SYSCALL_BASE+373)
	"__NR_sendmmsg		",//__NR_SYSCALL_BASE+374)
	"__NR_setns		",//__NR_SYSCALL_BASE+375)
	"__NR_process_vm_readv	",//__NR_SYSCALL_BASE+376)
	"__NR_process_vm_writev	",//__NR_SYSCALL_BASE+377)
	"__NR_kcmp		",//__NR_SYSCALL_BASE+378)
	"__NR_finit_module	",//__NR_SYSCALL_BASE+379)
	"__NR_sched_setattr	",//__NR_SYSCALL_BASE+380)
	"__NR_sched_getattr	",//__NR_SYSCALL_BASE+381)
	"__NR_renameat2		",//__NR_SYSCALL_BASE+382)
	"__NR_seccomp		",//__NR_SYSCALL_BASE+383)
	"__NR_getrandom		",//__NR_SYSCALL_BASE+384)
	"__NR_memfd_create	",//__NR_SYSCALL_BASE+385)
	"__NR_bpf		"};//__NR_SYSCALL_BASE+386)

#endif /* _DO_STRING_H */
